name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm i yarn -g
      - run: yarn install --frozen-lockfile

      - name: Build
        run: yarn docs:build


      - name: Zip the Build
        run: zip -r blogs.zip .vitepress/dist

      - name: Create Release and Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
            tag_name: V0.${{ github.run_id }}.dev
            name: V0.${{ github.run_id }}.dev
            body: TODO New Release.
            draft: false  # 是否是草稿
            prerelease: false # 是否是预览版
            files: |
              blogs.zip
              LICENSE
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .vitepress/dist
