name: Deploy

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm i yarn -g
      - run: yarn install --frozen-lockfile

      - name: Build
        run: yarn docs:build
      - name: Zip the Build
        run: zip -r blogs.zip .vitepress/dist
      - name: Create Release and Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
            tag_name: v1.${{ github.run_id }}
            name: blogs-v1.${{ github.run_id }}
            body: TODO New Release.
            draft: false  # 是否是草稿
            prerelease: true # 是否是预览版
            files: |
              blogs.zip
              LICENSE
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .vitepress/dist
            # 部署到服务器
      - name: Deploy-Server
        uses: appleboy/ssh-action@master
        with:
           host: ${{ secrets.HOST }} # 公网 IP 或 域名
           username: ${{ secrets.USERNAME }} # 登录名
           password: ${{ secrets.PASSWORD }} # 密码
           port: ${{ secrets.PORT }} # 端口
             # 类似在服务端的终端-执行以下操作
             # 1. 找到需要存放文件的地方
             # 2. 从 Github 上将 release.tgz 复制一份放入文件内
             # 3. 解压 release.tgz 文件
             # 4. 安装插件
           # 5. 重启 pm2, 并执行 pm2.config.json 内操作，
           # 6. pm2.config.json 是 启动 项目，( npm start )
           script: |
             cd  /home/blogs
             wget https://github.com/xieguanhua/xieguanhua.github.io/archive/refs/tags/v1.${{ github.run_id }}.zip
             unzip -o v1.${{ github.run_id }}.zip
             rm -rf v1.${{ github.run_id }}.zip

              
